[features]
seeds = false
skip-lint = false
[programs.devnet]
test = "3joWEmJ4LkanMRPR5yFqXKU3zoy41kkw6mGjc8crpV55"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mud/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
