[features]
seeds = false
skip-lint = false
[programs.devnet]
test = "7xd5qmpcKx3BPRJZLduGmvjxSXPoDuTFBHt9UDMBVCjH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/muddahlan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
