[features]
seeds = false
skip-lint = false
[programs.localnet]
test = "8Ph1EN9S7HLo4yrDVFWXChe27ixWhuQTdryPyYc5a24b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mud/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
