[features]
seeds = false
skip-lint = false
[programs.localnet]
test = "Cjn97wB2nmcrAeaTtMNSfAqNiVZdBhPLUd9pXDMHdagS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mud/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
